package Interface;

import Business.*;
import javax.swing.BoxLayout;
/**
 *
 * @author Bohan Feng
 */
public class CarListView extends javax.swing.JPanel {

    private CarList displayCarList, carlist;
    /**
     * Creates new form CarListView
     */
    public CarListView(CarList cl, CarList theTable) {
        initComponents();   
        this.setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        this.displayCarList = cl;
        this.carlist = theTable;
        getAvaliable();
        displayList();
    }
    
    private void getAvaliable(){
        txtAvaliable.setText(displayCarList.getNumOfAvaliableCars() + " ");
        txtUnavaliable.setText(displayCarList.getNumOfUnavaliableCars() + " ");
    }
    
    private void displayList(){
        try{
            for(Car c : displayCarList){
                CarListViewItemTemplate cItem = new CarListViewItemTemplate(c, carlist);
                this.add(cItem);
            } 
        }catch(java.lang.NullPointerException e){
            javax.swing.JOptionPane.showMessageDialog(null, 
                        "Nothing Found");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAvaliable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUnavaliable = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Avaliable Cars:");
        jPanel1.add(jLabel1);

        txtAvaliable.setText("jLabel2");
        jPanel1.add(txtAvaliable);

        jLabel3.setText("Unavaliable Cars");
        jPanel1.add(jLabel3);

        txtUnavaliable.setText("jLabel4");
        jPanel1.add(txtUnavaliable);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAvaliable;
    private javax.swing.JLabel txtUnavaliable;
    // End of variables declaration//GEN-END:variables
}
