package Interface;

/**
 *
 * @author Bohan
 */


import Business.*;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


public class MainFrame extends javax.swing.JFrame {

    
    public static Color whiteColor = new Color(192,192,200);
    public static Color lightColor = new Color(31,186,214);
    public static Color midColor = new Color(34,34,51);
    public static Color darkColor = new Color(22,22,41);
    public static Color blackColor = new Color(9,9,26);
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    
    private CarList carlist;
    private static List<List<String>> cars;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws IOException {
        initComponents();
        this.setTitle("Car Fleet Management");
        readFile();
        carlist = getCars();
    }
    
    public static void readFile() throws FileNotFoundException, IOException{
        cars = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("carsData\\out.csv"))) {
            String line;
            br.readLine();
            while ((line = br.readLine()) != null) {
                String COMMA_DELIMITER = ",";
                String[] values = line.split(COMMA_DELIMITER);
                cars.add(Arrays.asList(values));
            }
        }
        
        int i = 0;
        while(i < 5){
            for(String s : cars.get(i)){
                System.out.print(s + ",");
            }
            System.out.println();
            i++;
        }
    
        System.out.println();
    }
    
    public static CarList getCars(){
        CarList carlist = new CarList();
        for(List<String> carInfo : cars){
            Car carToAdd = new Car();
            String[] uptime = carInfo.get(7).split("/");
            String[] maintaintime = carInfo.get(8).split("/");
            carToAdd.setIsAvaliable(carInfo.get(0).equals("True"));
            carToAdd.setMaker(carInfo.get(1));
            carToAdd.setManufactureYear(Integer.parseInt(carInfo.get(2)));
            carToAdd.setSeatNum(Integer.parseInt(carInfo.get(3)));
            carToAdd.setSeriesNum(carInfo.get(4));
            carToAdd.setModel(carInfo.get(5));
            carToAdd.setCity(carInfo.get(6));
            carToAdd.setUpdateTime(new Date(Integer.parseInt(uptime[2])-1900,Integer.parseInt(uptime[0])-1,Integer.parseInt(uptime[1])));
            carToAdd.setMaintanceExpiredDate(new Date(Integer.parseInt(maintaintime[2])-1900,Integer.parseInt(maintaintime[0])-1,Integer.parseInt(maintaintime[1])));
          
            carlist.add(carToAdd);
        }
        return carlist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        btnPanelSearch = new javax.swing.JPanel();
        Text = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        btnPanelCreate = new javax.swing.JPanel();
        Text2 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setSize(new java.awt.Dimension(1000, 1500));

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(0);

        jPanel3.setBackground(new java.awt.Color(9, 9, 26));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanelSearch.setBackground(new java.awt.Color(31, 186, 214));
        btnPanelSearch.setPreferredSize(new java.awt.Dimension(166, 200));
        btnPanelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanelSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPanelSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPanelSearchMouseReleased(evt);
            }
        });

        Text.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("Search");

        icon.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/image/search420.png"))); // NOI18N

        javax.swing.GroupLayout btnPanelSearchLayout = new javax.swing.GroupLayout(btnPanelSearch);
        btnPanelSearch.setLayout(btnPanelSearchLayout);
        btnPanelSearchLayout.setHorizontalGroup(
            btnPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(Text)
                .addContainerGap())
        );
        btnPanelSearchLayout.setVerticalGroup(
            btnPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(btnPanelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 60));

        btnPanelCreate.setBackground(new java.awt.Color(31, 186, 214));
        btnPanelCreate.setPreferredSize(new java.awt.Dimension(166, 200));
        btnPanelCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPanelCreateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPanelCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPanelCreateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPanelCreateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPanelCreateMouseReleased(evt);
            }
        });

        Text2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Create");

        icon2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/image/plus220.png"))); // NOI18N

        javax.swing.GroupLayout btnPanelCreateLayout = new javax.swing.GroupLayout(btnPanelCreate);
        btnPanelCreate.setLayout(btnPanelCreateLayout);
        btnPanelCreateLayout.setHorizontalGroup(
            btnPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(Text2)
                .addContainerGap())
        );
        btnPanelCreateLayout.setVerticalGroup(
            btnPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPanelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Text2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(btnPanelCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logo Here");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 36)); // NOI18N
        jLabel1.setText("Car Fleet Management");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(233, 233, 233))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(1087, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelSearchMousePressed
        btnPanelSearch.setBackground(darkColor);
    }//GEN-LAST:event_btnPanelSearchMousePressed

    private void btnPanelSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelSearchMouseReleased
        btnPanelSearch.setBackground(lightColor);
    }//GEN-LAST:event_btnPanelSearchMouseReleased
   
    private void btnPanelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelSearchMouseEntered
        
    }//GEN-LAST:event_btnPanelSearchMouseEntered

    private void btnPanelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelSearchMouseExited
        
    }//GEN-LAST:event_btnPanelSearchMouseExited

    private void btnPanelCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCreateMouseEntered
        
    }//GEN-LAST:event_btnPanelCreateMouseEntered

    private void btnPanelCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCreateMouseExited
        
    }//GEN-LAST:event_btnPanelCreateMouseExited

    private void btnPanelCreateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCreateMousePressed
        btnPanelCreate.setBackground(darkColor);
    }//GEN-LAST:event_btnPanelCreateMousePressed

    private void btnPanelCreateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCreateMouseReleased
        btnPanelCreate.setBackground(lightColor);
    }//GEN-LAST:event_btnPanelCreateMouseReleased

    private void btnPanelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelSearchMouseClicked
        jSplitPane1.setRightComponent(new SearchPanel(this.carlist));
    }//GEN-LAST:event_btnPanelSearchMouseClicked

    private void btnPanelCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPanelCreateMouseClicked
        jSplitPane1.setRightComponent(new CreatePanel(this.carlist));
    }//GEN-LAST:event_btnPanelCreateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text2;
    private javax.swing.JPanel btnPanelCreate;
    private javax.swing.JPanel btnPanelSearch;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
