/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RetailCompany.PurchaseRole;

import UserInterface.FurnitureManufaCompany.PurchaseRole.*;
import Business.Account.Account;
import Business.WorkQueue.WorkRequest;
import EcoSystem.EcoSystem;
import System.Configure.DB4OUtil;
import UserInterface.Register.RegistForEnterpriseJPanel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bohan Feng
 */
public class CreateRequestJFrame extends javax.swing.JFrame {

    private Account account;
    private EcoSystem system;
    private PurchaseJPanel last;
    
    public CreateRequestJFrame(Account a, EcoSystem sys, PurchaseJPanel last) {
        initComponents();
        this.account = a;
        this.system = sys;
        this.last = last;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jtxWood = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxQuantity = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxOffer = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSubmit.setText("Sumbit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jtxWood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxWoodActionPerformed(evt);
            }
        });

        jLabel1.setText("Furniture Type");

        Quantity.setText("Quantity (lb)");

        jLabel3.setText("Offer Price ($)");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Quantity)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxWood, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxWood, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxWoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxWoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxWoodActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(inputValidate()){
            WorkRequest wr = new WorkRequest();
            String jsonString = "{"
                    + "\"ProductType\": \"" + jtxWood.getText() + "\","
                    + "\"Quantity\": \"" + jtxQuantity.getText() + "\","
                    + "\"BuyerOffer\": \"" + jtxOffer.getText() + "\","
                    + "\"SellerOffer\": \"\","
                    + "\"Seller\": {}"
                    + "}";
            wr.setMessage(jsonString);
            wr.setSender(account);
            wr.setStatus("Buyer submit request");
            wr.getReceivers().put(new Account(), true);

            // add request to queue
            try {
                system.getWorkQueue().addRequest(wr);
            } catch (Exception ex) {
                Logger.getLogger(RegistForEnterpriseJPanel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
                return;
            }

            JOptionPane.showMessageDialog(null, " Your repuest is submited, please wait for furniture manufacturer accept your request");
            DB4OUtil.storeSystem(system);
            last.populateTable();
            this.dispose();
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        this.setVisible(false); 
    }//GEN-LAST:event_btnCancelActionPerformed

     public boolean inputValidate(){
        if(jtxOffer.getText().isEmpty() || jtxQuantity.getText().isEmpty() 
                || jtxWood.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all text fields");
            return false;
        }
        
        try{
            Double.parseDouble(jtxQuantity.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "quantity should be numeric");
            return false;
        }
        
        try{
            Double.parseDouble(jtxOffer.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "your offer should be numeric");
            return false;
        }
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtxOffer;
    private javax.swing.JTextField jtxQuantity;
    private javax.swing.JTextField jtxWood;
    // End of variables declaration//GEN-END:variables
}
