/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Account.Account;
import Business.Enterprise.Enterprise;
import Business.WorkQueue.WorkRequest;
import EcoSystem.EcoSystem;
import javax.swing.JPanel;

/**
 *
 * @author Bohan Feng
 */
public class EnterpriseApproveInfoJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private JPanel container;
    private Account account;
    private WorkRequest workRequest;
    private EcoSystem system;
     
    private String PROCESS_MSG = "Your enterprise is not approved, please wait for system admin approve";
    private String DENIE_MSG = "Your EnterPrise is denined, please check you information and regist again";
    
    public EnterpriseApproveInfoJPanel(JPanel upc, EcoSystem s, Account a, Enterprise e) {
        initComponents();
        this.account =a;
        this.container = upc;
        this.enterprise = e;
        this.system = s;
        this.workRequest = system.getWorkQueue().getOneRequestBySender(a);
        populateInfo();
    }
    
    public void populateInfo(){
        this.jblApproved.setText(this.workRequest.getStatus().equals("Denied") ? "Denied" : "Not Approved");
        this.jblMsg.setText(this.workRequest.isIsCompleted() ? this.workRequest.getMessage() : PROCESS_MSG);
    }
    
    public void DestoryProfile(){
        system.getAccounts().removeAccount(account);
        system.getEnterprises().removeEnterprise(enterprise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblApproved = new javax.swing.JLabel();
        jblMsg = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();

        jblApproved.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jblApproved.setText("<isApproved>");

        jblMsg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jblMsg.setText("jLabel1");

        btnConfirm.setText("Comfirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblMsg)
                    .addComponent(jblApproved))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jblApproved)
                .addGap(44, 44, 44)
                .addComponent(jblMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        if(this.workRequest.isIsCompleted()){
            DestoryProfile();
        }
        CardLayoutNavigator.goBack(container, this);
    }//GEN-LAST:event_btnConfirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jblApproved;
    private javax.swing.JLabel jblMsg;
    // End of variables declaration//GEN-END:variables
}
