/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RetailCompany.SalesRole;

import Business.Enterprise.Enterprise;
import Business.Furniture.Furniture;
import EcoSystem.EcoSystem;
import System.Configure.DB4OUtil;
import UserInterface.ImgFilter;
import com.db4o.Db4o;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Bohan Feng
 */
public class FurtinureDetail extends javax.swing.JFrame {

    private EcoSystem system;
    private Furniture furniture;
    private Enterprise enterprise;
    private SalesWorkQueueJPanel last;
    private String filename;

    /**
     * Creates new form FurtinureDetail
     */
    public FurtinureDetail() {
        initComponents();
    }

    public FurtinureDetail(EcoSystem system, Furniture furniture, Enterprise enterprise, SalesWorkQueueJPanel last) {
        this();
        this.system = system;
        this.furniture = furniture;
        this.enterprise = enterprise;
        this.last = last;
        this.filename = furniture.getImage();
        populateContent();
    }

    public void populateContent() {
        jtxName.setText(furniture.getName());
        jtxType.setText(furniture.getType());
        jtxWood.setText(furniture.getWoodType());
        jtxColor.setText(furniture.getColor());
        jtxManu.setText(furniture.getManufacturer());
        jtxManu.enable(false);
        jtxSeller.setText(furniture.getSeller());
        jtxSeller.enable(false);
        jtxPrice.setText(furniture.getPrice() == null ? "" : furniture.getPrice() + "");
        jtxHeight.setText(furniture.getHeight() == null ? "" : furniture.getHeight() + "");
        jtxWidth.setText(furniture.getWidth() == null ? "" : furniture.getWidth() + "");
        jtxLength.setText(furniture.getLength() == null ? "" : furniture.getLength() + "");
        try {
            File imgFile = new File("./image/FurnitureImage/" + filename);
            setImg(imgFile);
        } catch (Exception e) {
            Picture.setText("file not found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        jtxName = new javax.swing.JTextField();
        jtxType = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        jtxWood = new javax.swing.JTextField();
        Name2 = new javax.swing.JLabel();
        jtxColor = new javax.swing.JTextField();
        Name3 = new javax.swing.JLabel();
        Name4 = new javax.swing.JLabel();
        jtxManu = new javax.swing.JTextField();
        jtxSeller = new javax.swing.JTextField();
        Name5 = new javax.swing.JLabel();
        jtxPrice = new javax.swing.JTextField();
        Name6 = new javax.swing.JLabel();
        Name7 = new javax.swing.JLabel();
        jtxHeight = new javax.swing.JTextField();
        Name8 = new javax.swing.JLabel();
        jtxWidth = new javax.swing.JTextField();
        Name9 = new javax.swing.JLabel();
        jtxLength = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Picture = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Name.setText("Name");

        Name1.setText("Type");

        Name2.setText("Wood");

        Name3.setText("Color");

        Name4.setText("Manufacturer");

        Name5.setText("Seller");

        Name6.setText("Price");

        Name7.setText("Height");

        Name8.setText("Width");

        Name9.setText("Length");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(100, 100, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnUpload.setBackground(new java.awt.Color(255, 255, 255));
        btnUpload.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        btnUpload.setText("Upload Image");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(Name1)
                    .addComponent(Name2)
                    .addComponent(Name3)
                    .addComponent(Name5)
                    .addComponent(Name6)
                    .addComponent(Name7)
                    .addComponent(Name8)
                    .addComponent(Name4)
                    .addComponent(Name9))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxLength, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxType, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxWood, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(114, 114, 114)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxManu, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(jtxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name1)
                            .addComponent(jtxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name2)
                            .addComponent(jtxWood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name3)
                            .addComponent(jtxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name4)
                            .addComponent(jtxManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name5)
                            .addComponent(jtxSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name6)
                    .addComponent(jtxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name7)
                    .addComponent(jtxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name8)
                    .addComponent(jtxWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name9)
                    .addComponent(jtxLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        createChooserWindow((JFrame) SwingUtilities.getWindowAncestor(this));
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (inputValidate()) {
            furniture.setName(jtxName.getText());
            furniture.setType(jtxType.getText());
            furniture.setWoodType(jtxWood.getText());
            furniture.setColor(jtxColor.getText());
            if (!jtxPrice.getText().isEmpty()) {
                furniture.setPrice(Double.parseDouble(jtxPrice.getText()));
            }
            if (!jtxHeight.getText().isEmpty()) {
                furniture.setHeight(Double.parseDouble(jtxHeight.getText()));
            }
            if (!jtxWidth.getText().isEmpty()) {
                furniture.setWidth(Double.parseDouble(jtxWidth.getText()));
            }
            if (!jtxLength.getText().isEmpty()) {
                furniture.setLength(Double.parseDouble(jtxLength.getText()));
            }
            furniture.setImage(filename);
            DB4OUtil.storeSystem(system);
            JOptionPane.showMessageDialog(null, "furnirure imformation saved");
            last.popupateTable();

            this.dispose();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private boolean inputValidate() {
        if (jtxName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "furniture name cannot be empty");
            return false;
        }

        if (!jtxPrice.getText().isEmpty()) {
            try {
                Double.parseDouble(jtxPrice.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "price should be numeric");
                return false;
            }
        }

        if (!jtxHeight.getText().isEmpty()) {
            try {
                Double.parseDouble(jtxHeight.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "price should be numeric");
                return false;
            }
        }

        if (!jtxWidth.getText().isEmpty()) {
            try {
                Double.parseDouble(jtxWidth.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "price should be numeric");
                return false;
            }
        }

        if (!jtxLength.getText().isEmpty()) {
            try {
                Double.parseDouble(jtxLength.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "price should be numeric");
                return false;
            }
        }

        return true;
    }

    private void createChooserWindow(JFrame frame) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImgFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(frame);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            setImg(file);
            try {
                Path temp = Files.move(Paths.get(file.getAbsolutePath()),
                        Paths.get("./image/FurnitureImage/" +file.getName()));
                if (temp != null) {
                    filename = file.getName();
                    System.out.println("File renamed and moved successfully");
                } else {
                    System.out.println("Failed to move the file");
                }
            } catch (IOException ex) {
                Logger.getLogger(FurtinureDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Picture.setText("");
        }
    }

    /**
     * this one display the image file in internal panel, and set data member to
     * person object
     *
     * @param file image file
     */
    private void setImg(File file) {
        try {
            BufferedImage myImg = ImageIO.read(file);
            Image dImg = myImg.getScaledInstance(200,
                    myImg.getHeight() * 200 / myImg.getWidth(),
                    Image.SCALE_SMOOTH);
            Picture.setIcon(new ImageIcon(dImg));
            Picture.setText("");
        } catch (IOException ex) {
            Picture.setText("no image");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JLabel Name7;
    private javax.swing.JLabel Name8;
    private javax.swing.JLabel Name9;
    private javax.swing.JLabel Picture;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxColor;
    private javax.swing.JTextField jtxHeight;
    private javax.swing.JTextField jtxLength;
    private javax.swing.JTextField jtxManu;
    private javax.swing.JTextField jtxName;
    private javax.swing.JTextField jtxPrice;
    private javax.swing.JTextField jtxSeller;
    private javax.swing.JTextField jtxType;
    private javax.swing.JTextField jtxWidth;
    private javax.swing.JTextField jtxWood;
    // End of variables declaration//GEN-END:variables
}
