/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LogisticCompany.LogisticRole;

import Business.Account.Account;
import Business.Enterprise.Enterprise;
import Business.Role.RoleType;
import Business.WorkQueue.WorkRequest;
import EcoSystem.EcoSystem;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Bohan Feng
 */
public class LocationDetailJFrame extends javax.swing.JFrame {

    public WorkRequest wr;
    private EcoSystem system;

    public LocationDetailJFrame(WorkRequest wr, EcoSystem sys) {
        initComponents();
        this.wr = wr;
        this.system = sys;
        populateContent();
        setButtonImage();
    }
    private void setButtonImage(){
         ImageIcon bargain=new ImageIcon("./image/confirm.png");
         jButton1.setIcon(bargain);
    }
    public void populateContent() {
        Account a = (new ArrayList<>(wr.getReceivers().keySet())).get(0);
        String state, city, street, zip;
        if(a.getRole().rType == RoleType.Customer){
            state = a.getPerson().getState();
            city = a.getPerson().getCity();
            street = a.getPerson().getStreet();
            zip = a.getPerson().getZipCode();
        }else{
            Enterprise e = system.getEnterprises().getEnterpriseByEmployeeAccount(
                    (new ArrayList<>(wr.getReceivers().keySet())).get(0)
            );
            state = e.getState();
            city = e.getCity();
            street = e.getStreet();
            zip = e.getZipCode();
            
        }
        
        txtState.setText(state == null ? "not avaliable" : state);
        txtCity.setText(city == null ? "not avaliable" : city);
        txtStreet.setText(street == null ? "not avaliable" : street);
        txtZip.setText(zip == null ? "not avaliable" : zip);
        txtReceiver.setText(a.getPerson() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        State = new javax.swing.JLabel();
        txtState = new javax.swing.JLabel();
        State1 = new javax.swing.JLabel();
        txtCity = new javax.swing.JLabel();
        txtStreet = new javax.swing.JLabel();
        State2 = new javax.swing.JLabel();
        State3 = new javax.swing.JLabel();
        txtZip = new javax.swing.JLabel();
        State4 = new javax.swing.JLabel();
        txtReceiver = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        State.setText("State");

        txtState.setText("<>");

        State1.setText("City");

        txtCity.setText("<>");

        txtStreet.setText("<>");

        State2.setText("Street");

        State3.setText("Zip Code");

        txtZip.setText("<>");

        State4.setText("Receiver");

        txtReceiver.setText("<>");

        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(State4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(State2)
                        .addComponent(State1)
                        .addComponent(State)
                        .addComponent(State3)))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtReceiver)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtState)
                                .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtStreet, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(txtZip))
                .addContainerGap(471, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State)
                    .addComponent(txtState))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State1)
                    .addComponent(txtCity))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State2)
                    .addComponent(txtStreet))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State3)
                    .addComponent(txtZip))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State4)
                    .addComponent(txtReceiver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel State;
    private javax.swing.JLabel State1;
    private javax.swing.JLabel State2;
    private javax.swing.JLabel State3;
    private javax.swing.JLabel State4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtCity;
    private javax.swing.JLabel txtReceiver;
    private javax.swing.JLabel txtState;
    private javax.swing.JLabel txtStreet;
    private javax.swing.JLabel txtZip;
    // End of variables declaration//GEN-END:variables
}
